### PR TITLE
Add minimal CMake build system + cover compilation with GitHub Actions

### PR DESCRIPTION
**Pull request by hartwork**
Hi! :wave: 

This pull request does four small interconnected things:
- Add a small CMake-based build system. CMake >=3.6 to be precise.
- Add a GitHub Action to build the code on Ubuntu Linux with recent GCC 11/12 and Clang 15/16/17. This will make sure that if the code starts failing to compile in the future we will know and have a chance to react. Example output can be seen at https://github.com/hartwork/AudioVisualiser/actions in my fork of this repository.
- Add a missing include `#include <memory>` to fix compilation for all of these^^ except GCC 11. Compilers get stricter over time.
- Activate GitHub Dependabot to keepu our Github Actions up to date so that I will create pull requests like https://github.com/uriparser/uriparser/pull/159 for us in the future

Regarding the license of the new files, I have put in "Licensed under GPL v3 or later" for the moment, but I'm happy to put in some other license that is Open Source according to OSI and Free Software according to the FSF, e.g. BSD, MIT, Apache 2.
I looked for mention of "copyright" and "license" in here and didn't find any for your own code. Would be great if we could apply some license like that — copyleft or permissive — to that code too. I can make a new pull request on that if you like if you let me know which license and e-mail address to user for the header.

What do you think?

Best, Sebastian

### CODE REVIEW

**Comment by hartwork** [comment]
@JanKleprlik any thoughts?

**Comment by hartwork** [comment]
Hi @JanKleprlik I made this pull request because you said that you would "gladly accept [my] PR" at https://github.com/JanKleprlik/AudioVisualiser/issues/1#issuecomment-1418252593 . I've been trying to reach you via e-mail two times without luck and I'm waiting for action here for literally months now. Could you please get back to communicating with me? Thank you!

**Comment by JanKleprlik** [comment]
Hey, yes sorry. I am not aware of any emails. I must have missed them. I am terribly sorry for that, my bad. 

Good job on the yaml! All lgtm including the licence. I will merge immediately. And sorry again for keeping you waiting.

**Comment by hartwork** [comment]
Hi @JanKleprlik thanks for your reply and the merge :pray: 

My mails went to `kleprlikjan(add)gmail(dort)com` on 2023-02-28 and 2023-03-06, subject was "AudioVisualiser / pull request". Is that address alive today?

One important piece is still missing: My new files are still the only ones currently carrying license information. If you liked "Licensed under GPL v3 or later" for a license on my files, would you be up for applying the same license to your own files? Best practice would be a header for each source file plus a COPYING or LICENSE file with the file text. I can make a pull request if you like. What do you think?

**Comment by JanKleprlik** [comment]
I see the emails now. So sorry for not replying.

I don't think it's necessary to add it, but if you think it would be beneficial, feel free to create a new PR. I can add the LICENCE file myself in the evening. 

One note: there is a copy of the SFML library (not distributed via nugget at the time of writing the code) which is under another licence. How would that work? Would we have to mention it somewhere explicitly?

**Comment by hartwork** [comment]
@JanKleprlik regarding SFML, it seems to be licensed under the [zlib license](https://en.wikipedia.org/wiki/Zlib_License) which is rather liberal and compatible to the GPL. If your code was zlib license and SFML was GPL — the other way around — that would not work, but this way around does, not an easy topic. I believe there is nothing more needed in terms of licensing with regard to SFML.

For the headers I have now created pull request #4.

**Pull request merged**
